version: '3.5'

services:
  postgres:
    container_name: postgres_registry
    image: postgres:14.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgres/data



volumes:
   pg_data:
      driver: local