version: '3.5'
services:
  postgres:
    container_name: giz-postgres
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - dockernetwork
    volumes:
      - pg_data:/var/lib/postgres/data
volumes:
   pg_data:
      driver: local
networks:
  dockernetwork:
    name: dockernetwork
    driver: bridge
