server:
  port: 8081
spring:
  application:
    name: ibr-service
  jackson:
    default-property-inclusion: non-null

  datasource:
    url: jdbc:postgresql://localhost:5432/ibrDB
    username: postgres
    password: W@nder@2024
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
       SQL:
         DEBUG